### ISSUE TITLE
Customize bubble color?

### ISSUE THREAD

**Issue by yarodevuci** [QuickBlox/ChatMessagesAdapter-android#15]
Is there a way to customize chat bubble color? Or how to use my own chat bubble views for text messages

**Comment by RomanPronin** [comment]
Hi, @yarodevuci. You can customize any view element in ChatAdapter. As for bubble, let's say for left side opponent, you can just create style:
`<style name="BubbleTextFrame.Left">`
       ` <item name="android:background">@drawable/left_bubble</item>`
`...`
    `</style>`
and set any attribute you need.
For more info look [here](https://github.com/QuickBlox/ChatMessagesAdapter-android/blob/master/README.md).

**Comment by RomanPronin** [comment]
Any updates?
