### ISSUE TITLE
How Can I show message statues sign??

### ISSUE THREAD

**Issue by kyrloseshak** [QuickBlox/ChatMessagesAdapter-android#17]
i have tried Chat message Adapter and it works perfect for me but i couldn't make a message statues sign like : sent , delivered or seen like messanger or whattsApp, can you help me Please??

**Comment by RomanPronin** [comment]
Hi, @kyrloseshak. In your app create [list_item_text_right](https://github.com/QuickBlox/q-municate-android/blob/master/Q-municate_app/src/main/res/layout/list_item_text_right.xml), where "widget_id_bottom" must be defined with your [layout with ImageView](https://github.com/QuickBlox/q-municate-android/blob/master/Q-municate_app/src/main/res/layout/custom_msg_right_bottom_widget.xml).
Now in your adapter in onBindViewMsgRightHolder
`ImageView view = (ImageView) holder.itemView.findViewById(R.id.message_status_image_view);`
` imageView.setImageResource(R.drawable.ic_status_mes_sent);`
Look at this [PrivateChatMessageAdapter](https://github.com/QuickBlox/q-municate-android/blob/master/Q-municate_app/src/main/java/com/quickblox/q_municate/ui/adapters/chats/PrivateChatMessageAdapter.java) in Q-mun project for details.

**Comment by RomanPronin** [comment]
Any updates?

**Comment by kyrloseshak** [comment]
Here Is my code and i can't get the Seen Sign displayed

public class CustomMessageAdapter  extends QBMessagesAdapter<QBChatMessage> {
private static final String TAG = CustomMessageAdapter.class.getSimpleName();
protected static final int TYPE_OWN_VIDEO_ATTACH = 5;
protected static final int TYPE_OPPONENT_VIDEO_ATTACH = 6;

private QBUser currentUser = new QBUser();
private QBUser opponentUser= new QBUser();
private String opponentUserName;
private Context mContext;
private DateFormat df = new SimpleDateFormat("EEE,MMM d,yyyy - HH:mm");
    MediaPlayer mp;

public CustomMessageAdapter(Context context, List<QBChatMessage> chatMessages, String opponentName) {
    super(context, chatMessages);
    this.mContext = context;
    this.opponentUserName = opponentName;
}




@Override
protected int customViewType(int position) {
    QBChatMessage chatMessage = getItem(position);

    if (hasAttachments(chatMessage)) {
        QBAttachment attachment = chatMessage.getAttachments().iterator().next();
        if (QBAttachment.VIDEO_TYPE.equals(attachment.getType())) {
            return isIncoming(chatMessage) ? TYPE_OPPONENT_VIDEO_ATTACH : TYPE_OWN_VIDEO_ATTACH;
        }
        else if (QBAttachment.PHOTO_TYPE.equalsIgnoreCase(attachment.getType()) ||
                QBAttachment.IMAGE_TYPE.equalsIgnoreCase(attachment.getType())) {
            return isIncoming(chatMessage) ? TYPE_ATTACH_LEFT : TYPE_ATTACH_RIGHT;
        } else if (QBAttachment.LOCATION_TYPE.equalsIgnoreCase(attachment.getType())) {
            return getLocationView(chatMessage);
        } else if (QBAttachment.AUDIO_TYPE.equalsIgnoreCase(attachment.getType())) {
            return isIncoming(chatMessage) ? TYPE_ATTACH_LEFT_AUDIO : TYPE_ATTACH_RIGHT_AUDIO;
        }
    }
    return -1;
}



        @Override
protected void onBindViewCustomHolder(QBMessageViewHolder holder, QBChatMessage chatMessage, int position) {
        displayAttachment(holder, position);
        holder.avatar.setVisibility(View.GONE);
        }

        @Override
        protected void onBindViewAttachLeftHolder(ImageAttachHolder holder, QBChatMessage chatMessage, int position) {
                holder.avatar.setVisibility(View.GONE);
                MediaPlayer.create(mContext, R.raw.recieved).start();

                super.onBindViewAttachLeftHolder(holder, chatMessage, position);
        }

        @Override
        protected void onBindViewAttachRightHolder(ImageAttachHolder holder, QBChatMessage chatMessage, int position) {
                holder.avatar.setVisibility(View.GONE);

                super.onBindViewAttachRightHolder(holder, chatMessage, position);
        }

    @Override
    protected void onBindViewAttachLeftAudioHolder(AudioAttachHolder holder, QBChatMessage chatMessage, int position) {
        this.setDateSentAttach(holder, chatMessage);
        this.displayAttachmentAudio(holder, position);
        int valueType = this.getItemViewType(position);
        holder.avatar.setVisibility(View.GONE);
        MediaPlayer.create(mContext, R.raw.recieved).start();

        super.onBindViewAttachLeftAudioHolder(holder, chatMessage, position);
    }

    @Override
    protected void onBindViewAttachRightAudioHolder(AudioAttachHolder holder, QBChatMessage chatMessage, int position) {
        this.setDateSentAttach(holder, chatMessage);
        this.displayAttachmentAudio(holder, position);
        int valueType = this.getItemViewType(position);
        holder.avatar.setVisibility(View.GONE);
        super.onBindViewAttachRightAudioHolder(holder, chatMessage, position);
    }

    @Override
protected void onBindViewMsgRightHolder(TextMessageHolder holder, QBChatMessage chatMessage, int position) {
      //  TextView view = (TextView) holder.itemView.findViewById(R.id.custom_text_view);
        holder.timeTextMessageTextView.setTextSize(12f);
        Collection<Integer> idDelivered = null;
        idDelivered = chatMessage.getDeliveredIds();
        Collection<Integer> idRead = null;
        idRead = chatMessage.getReadIds();
        boolean delivered = false;
        boolean read = false;

        if (idDelivered!=null)
        {
            try {
                for (int i=0 ;i<idDelivered.size();i++)
                {
                    if (idDelivered.contains(chatMessage.getRecipientId()))
                    {
                        delivered=true;
                    }

                }
            } catch (NullPointerException e) {
                e.printStackTrace();
            }
        }
        if (idRead!=null)
        {
            try {
                for (int i=0 ;i<idRead.size();i++)
                {
                    if (idRead.contains(chatMessage.getRecipientId()))
                    {
                        read=true;
                    }
            }
            } catch (NullPointerException e) {
                e.printStackTrace();
            }


        }

      ImageView iv_sent = (ImageView) holder.itemView.findViewById(R.id.message_status_image_view);
        if (chatMessage.isMarkable())
        {
            setMessageStatus(iv_sent, delivered,read);
        } else {
            iv_sent.setImageResource(android.R.color.transparent);
        }


       /* view.setText(currentUser.getFullName());
        view.setTextColor(mContext.getResources().getColor(R.color.white));*/
        holder.messageTextView.setTextColor(mContext.getResources().getColor(R.color.white));
        holder.timeTextMessageTextView.setTextColor(mContext.getResources().getColor(R.color.white));
        holder.avatar.setVisibility(View.GONE);
        super.onBindViewMsgRightHolder(holder, chatMessage, position);
        }

@Override
protected void onBindViewMsgLeftHolder(TextMessageHolder holder, QBChatMessage chatMessage, int position) {
        //holder.timeTextMessageTextView.setVisibility(View.GONE);
        holder.timeTextMessageTextView.setTextSize(12f);
        TextView textView = (TextView) holder.itemView.findViewById(R.id.opponent_name_text_view);
        textView.setText(opponentUserName);
        holder.avatar.setVisibility(View.GONE);
        MediaPlayer.create(mContext, R.raw.recieved).start();

         holder.messageTextView.setTextColor(mContext.getResources().getColor(R.color.black));

       /* TextView customMessageTimeTextView = (TextView) holder.itemView.findViewById(R.id.custom_msg_text_time_message);
        customMessageTimeTextView.setText(getDate(chatMessage.getDateSent()));*/

        super.onBindViewMsgLeftHolder(holder, chatMessage, position);
        }



        @Override
        protected String getDate(long seconds) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("dMMM,yyyy - HH:mm", Locale.getDefault());
                return dateFormat.format(new Date(seconds * 1000L));
        }

    protected void setMessageStatus(ImageView imageView, boolean messageDelivered, boolean messageRead) {
        if (messageDelivered)
        {
            imageView.setImageResource(R.drawable.delivered_message);
        }
        if (messageRead)
            {
                imageView.setImageResource(R.drawable.read_message);
            }

    }

    @Override
    public int getItemCount() {
        if (this.chatMessages == null)
            return 0;
        else
            return  this.chatMessages.size();
    }
}

**Comment by RomanPronin** [comment]
Did you add list_item_text_right.xml to your project?
`<?xml version="1.0" encoding="utf-8"?>`
`<com.quickblox.ui.kit.chatmessage.adapter.widget.MessageTextViewRight` `xmlns:android="http://schemas.android.com/apk/res/android"`
   ` xmlns:custom="http://schemas.android.com/apk/res-auto"`

    android:id="@+id/msg_message_text_view_right"
    style="@style/ListItemTextMessage.Right"
    custom:widget_id_bottom="@layout/custom_msg_right_bottom_widget">

`</com.quickblox.ui.kit.chatmessage.adapter.widget.MessageTextViewRight>`

where "widget_id_bottom" is a layout "custom_msg_right_bottom_widget" with ImageView:

`<?xml version="1.0" encoding="utf-8"?>`
`<ImageView android:id="@+id/message_status_image_view"`
    `android:layout_width="match_parent"`
   ` android:layout_height="match_parent"`
   ` android:layout_gravity="top"`
    `android:scaleType="fitCenter"`
    `android:paddingLeft="5dp"`
    `xmlns:android="http://schemas.android.com/apk/res/android" />`

**Comment by kyrloseshak** [comment]
It's now appear , but i cant find the code that change it 

Here is my code 👍 

protected void onBindViewMsgRightHolder(TextMessageHolder holder, final QBChatMessage chatMessage, int position) {
      //  TextView view = (TextView) holder.itemView.findViewById(R.id.custom_text_view);
        holder.timeTextMessageTextView.setTextSize(12f);

      iv_sent = (ImageView) holder.itemView.findViewById(R.id.message_status_image_view);

      iv_sent.setImageResource(R.drawable.delivered_message);
        messageStatusListener = new QBMessageStatusListener() {
            @Override
            public void processMessageDelivered(String messageId, String dialogId, Integer userId)
            {
                if (chatMessage.getId()==messageId||chatMessage.getId().equals(messageId))
                {
                    setMessageStatus(iv_sent, true,false);
                    Toast.makeText(mContext, "Delivered", Toast.LENGTH_SHORT).show();
                }
            }

            @Override
            public void processMessageRead(String messageId, String dialogId, Integer userId)
            {
                if (chatMessage.getId()==messageId||chatMessage.getId().equals(messageId))
                {
                    setMessageStatus(iv_sent, false,true);
                    Toast.makeText(mContext, "Read", Toast.LENGTH_SHORT).show();

                }
            }
        };

        try {
            messageStatusesManager.addMessageStatusListener(messageStatusListener);
        } catch (NullPointerException e) {
            e.printStackTrace();
        }
        holder.messageTextView.setTextColor(mContext.getResources().getColor(R.color.white));
        holder.timeTextMessageTextView.setTextColor(mContext.getResources().getColor(R.color.white));
        holder.avatar.setVisibility(View.GONE);
        super.onBindViewMsgRightHolder(holder, chatMessage, position);
        }

 protected void setMessageStatus(ImageView imageView, boolean messageDelivered, boolean messageRead) {
        if (messageDelivered)
        {
            imageView.setImageResource(R.drawable.delivered_message);
        }
        if (messageRead)
            {
                imageView.setImageResource(R.drawable.read_message);
            }

    }

Can you Help Me because i can't implement  PrivateChatMessageAdapter in Q-mun project.

**Comment by RomanPronin** [comment]
Is your problem still actual?

**Comment by RomanPronin** [comment]
longtime inactivity

**Comment by Nikhil-z** [comment]
I have the similar issue. I'm not using the new Q-municate. So how can I achieve the message delivery image updates from chat adapter? I have implemented both layouts in my app.
