### ISSUE TITLE
Ho wo to add date header for messages i.e. Today, yesterday, or specific date

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/ChatMessagesAdapter-android#18]
![untitled](https://user-images.githubusercontent.com/5007881/33010910-fd75cea4-cdfd-11e7-9202-fa57e7917fd8.png)

**Comment by RomanPronin** [comment]
Hello @Shahjahan786. You should create your ChatAdapter class, then extends it from QBMessagesAdapter and , for example, implement [StickyRecyclerHeadersAdapter()](https://github.com/timehop/sticky-headers-recyclerview) or another one.
