### ISSUE TITLE
Send message not work

### ISSUE THREAD

**Issue by Naguchennai** [QuickBlox/ChatMessagesAdapter-android#2]
Send message not work

  ` button_chat_send.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(ChatActivity.this, "this is my Toast message!!! =)", Toast.LENGTH_LONG).show();
                try {
                    QBChatMessage chatMessage = new QBChatMessage();
                    chatMessage.setBody("Hi there!");
                    chatDialog.sendMessage(chatMessage);
                } catch (SmackException.NotConnectedException e) {

                }

            }
        });`

Attempt to invoke virtual method 'void com.quickblox.chat.QBAbstractChat.sendMessage(com.quickblox.chat.model.QBChatMessage)' on a null object reference

**Comment by RomanPronin** [comment]
Sending message shouldn't work. This sample just shows an implementation of ChatAdapter kit.
