### ISSUE TITLE
Play audio record programatically 

### ISSUE THREAD

**Issue by axionnneeeel** [QuickBlox/ChatMessagesAdapter-android#25]
Hello, how can i play audio record programatically? You mentioned QBPlaybackControlView  but i can't figure out how to play it having adapter position and uri. I succeded in playing video programatically with VideoPlayerActivity but i can't find out how to do it with audio too..

**Comment by RomanPronin** [comment]
Hi @axionnneeeel, to start play audio, you can use the next:
```
QBMessagesAdapter.AudioAttachHolder holder = (QBMessagesAdapter.AudioAttachHolder) messagesRecyclerView.findViewHolderForAdapterPosition(positionInAdapter);
mediaManager.playMedia(holder.playerView, uri);
//for pause
 mediaManager.pauseMedia();
```
Or use directly ExoPlayer:
```
SimpleExoPlayer player = SimpleExoPlayerInitializer.initializeExoPlayer(context);
player.prepare(SimpleExoPlayerInitializer.buildMediaSource(uri, context));

player.setPlayWhenReady(true);

**Comment by axionnneeeel** [comment]
Thanks
