### ISSUE TITLE
Override VideoPlayerActivity gestures 

### ISSUE THREAD

**Issue by axionnneeeel** [QuickBlox/ChatMessagesAdapter-android#26]
Is there a way to override VideoPlayerActivity swipe gesture? I am using a viewpager to slide between chat videos and images and i can't get the desired result. It's working fine for images only.

**Comment by RomanPronin** [comment]
I'd recommend you to create your own VideoPlayerFragment with your logic (as an example of video playback use [VideoPlayerActivity](https://github.com/QuickBlox/ChatMessagesAdapter-android/blob/a5e545b2548c36de926fcc264d37e43a19065acf/chat-message-adapter/src/main/java/com/quickblox/ui/kit/chatmessage/adapter/media/video/ui/VideoPlayerActivity.java#L27)) and use [FragmentStatePagerAdapter](https://developer.android.com/reference/android/support/v4/app/FragmentStatePagerAdapter)

**Comment by axionnneeeel** [comment]
In the end I used SimpleExoPlayer from your VideoPlayerActivity. Working fine now. Thanks.
