### ISSUE TITLE
 Supertypes of the following classes cannot be resolved

### ISSUE THREAD

**Issue by devganiyahitesh1** [QuickBlox/ChatMessagesAdapter-android#30]
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.quickblox.ui.kit.chatmessage.adapter.media.view.QBPlaybackControlView, unresolved supertypes: com.google.android.exoplayer2.ui.PlaybackControlView
    class com.quickblox.ui.kit.chatmessage.adapter.media.SingleMediaManager, unresolved supertypes: com.google.android.exoplayer2.Player.EventListener

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: zjurqxsrvp

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?
