### ISSUE TITLE
Please VideocallAdapter too

### ISSUE THREAD

**Issue by lordmen99** [QuickBlox/ChatMessagesAdapter-android#4]
For chat now have already adapter, can team build videocalladapter please

**Comment by RomanPronin** [comment]
Hello @lordmen99. Yes, we are going to create videocall adapter approximately at the end of the first quarter of the year.

**Comment by lordmen99** [comment]
Great, i try integration with latest sdk, but make me confius. can help me with simple code for videocall??

**Comment by RomanPronin** [comment]
Sure. What is your problem?

**Comment by lordmen99** [comment]
i want add, when user click icon videocall will direct make videocall . i try use already code, need load opponent etc.. its make too long.

**Comment by RomanPronin** [comment]
You may have a look at [Q-mun app](https://github.com/QuickBlox/q-municate-android). There are also implemented video calls peer to peer.
